# **Python pandas:**

# **What is pandas?**

pandas is a data manipulation package in Python for tabular data. That is, data in the form of rows and columns, also known as DataFrames. Intuitively, you can think of a DataFrame as an Excel sheet.

Pandas’ functionality includes data transformations, like sorting rows and taking subsets, to calculating summary statistics such as the mean, reshaping DataFrames, and joining DataFrames together. pandas works well with other popular Python data science packages, often called the PyData ecosystem, including

* NumPy for numerical computing

* Matplotlib, Seaborn, Plotly, and other data visualization packages

* scikit-learn for machine learning

**What is pandas used for?**

pandas is used throughout the data analysis workflow. With pandas, you can:

* Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more.

* Clean datasets, for example, by dealing with missing values.
Tidy datasets by reshaping their structure into a suitable format for analysis.

* Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more.

* Visualize datasets and uncover insights.

# **Key benefits of the pandas package:**

Undoubtedly, pandas is a powerful data manipulation tool packaged with several benefits, including:

* Made for Python: Python is the world's most popular language for machine learning and data science.

* Less verbose per unit operations: Code written in pandas is less verbose, requiring fewer lines of code to get the desired output.

* Intuitive view of data: pandas offers exceptionally intuitive data representation that facilitates easier data understanding and analysis.

* Extensive feature set: It supports an extensive set of operations from exploratory data analysis, dealing with missing values, calculating statistics, visualizing univariate and bivariate data, and much more.

* Works with large data: pandas handles large data sets with ease. It offers speed and efficiency while working with datasets of the order of millions of records and hundreds of columns, depending on the machine.

# **Importing data in pandas:**

To begin working with pandas, import the pandas Python package as shown below. When importing pandas, the most common alias for pandas is pd.

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)  # Prints the pandas version

2.2.2

# **Creating a DataFrame :**
A DataFrame is like a table with rows and columns. **Create student dataframe that has the following column (See the output)**

In [ ]:
import pandas as pd

      Name  Age Favorite_Subject  Test_Score
0    Alice   12             Math          85
1      Bob   11          Science          92
2  Charlie   12              Art          78
3    Diana   11             Math          88
4      Eve   12          English          95

**Create student dataframe using the following list:**

In [ ]:
# From a List
data1 = [
    ['Alice', 25, 'London'],
    ['Bob', 30, 'Paris'],
    ['Charlie', 35, 'Berlin']
]

      Name  Age    City
0    Alice   25  London
1      Bob   30   Paris
2  Charlie   35  Berlin

# **Reading and Writing CSV Files**

Explanation:
CSV (Comma-Separated Values) is a common format for datasets.

* Use pd.read_csv() to load data from a CSV file.

* Use df.to_csv() to save a DataFrame as a CSV file.

In [ ]:
# Write the DataFrame to CSV
df.to_csv('students.csv', index=False)

# Read it back
df_csv = pd.read_csv('students.csv')
df_csv.head()

      Name  Age Favorite_Subject  Test_Score
0    Alice   12             Math          85
1      Bob   11          Science          92
2  Charlie   12              Art          78
3    Diana   11             Math          88
4      Eve   12          English          95

# **Exploring Data:**

Explanation:
You can quickly explore data with built-in Pandas methods.

In [ ]:
df.info()         # Overview of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              5 non-null      object
 1   Age               5 non-null      int64
 2   Favorite_Subject  5 non-null      object
 3   Test_Score        5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

 **Statistical summary:**

In [ ]:
df.describe()     # Statistical summary

             Age  Test_Score
count   5.000000    5.000000
mean   11.600000   87.600000
std     0.547723    6.580274
min    11.000000   78.000000
25%    11.000000   85.000000
50%    12.000000   88.000000
75%    12.000000   92.000000
max    12.000000   95.000000

In [ ]:
df.shape          # Dimensions (rows, columns)

(5, 4)

In [ ]:
df.columns        # List of column names

Index(['Name', 'Age', 'Favorite_Subject', 'Test_Score'], dtype='object')

In [ ]:
df.dtypes         # Data types

Name                object
Age                  int64
Favorite_Subject    object
Test_Score           int64
dtype: object

In [ ]:
# Display basic information about the dataset
print("Dataset Overview:")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print("\nColumn information:")
print(df.dtypes)

# **Selecting Data**

Explanation:
You can select columns or rows using `.loc[], .iloc[],` or bracket notation.

### **Selecting Columns:**

**Select one column of your choice using pandas:**

In [ ]:
# Select one column

0      Alice
1        Bob
2    Charlie
3      Diana
4        Eve
Name: Name, dtype: object

**Select more than one column of your choice:**

In [ ]:
# Get multiple columns

      Name  Test_Score
0    Alice          85
1      Bob          92
2  Charlie          78
3    Diana          88
4      Eve          95

### **Selecting Rows :**

In [ ]:
df.loc[0]                        # Select first row (by label)

Name                Alice
Age                    12
Favorite_Subject     Math
Test_Score             85
Name: 0, dtype: object

In [ ]:
df.iloc[2]                       # Select third row (by index)

Name                Charlie
Age                      12
Favorite_Subject        Art
Test_Score               78
Name: 2, dtype: object

In [ ]:
# Get multiple rows
df.iloc[0:3] # First three rows

      Name  Age Favorite_Subject  Test_Score
0    Alice   12             Math          85
1      Bob   11          Science          92
2  Charlie   12              Art          78

In [ ]:
df.loc[0:2, ['Name', 'Age']]     # Slice by label

      Name  Age
0    Alice   12
1      Bob   11
2  Charlie   12

# **Filtering Data**

Explanation:
Use conditional statements to filter rows.

**Filter the dataframe using Test_score of students > 85**

In [ ]:
# Students who scored above 85

    Name  Age Favorite_Subject  Test_Score
1    Bob   11          Science          92
3  Diana   11             Math          88
4    Eve   12          English          95

**Filter the dataframe using the Age column == 12:**

In [ ]:
# Students aged 12

      Name  Age Favorite_Subject  Test_Score
0    Alice   12             Math          85
2  Charlie   12              Art          78
4      Eve   12          English          95

**Filter the dataframe using the Favorite_subject == Math:**

In [ ]:
# Students who like Math

    Name  Age Favorite_Subject  Test_Score
0  Alice   12             Math          85
3  Diana   11             Math          88

**Filter the frame by Age and Test_Score:**

In [ ]:
# Multiple conditions (AND)

    Name  Age Favorite_Subject  Test_Score
0  Alice   12             Math          85
4    Eve   12          English          95


**Filter the frame by either by Math or Science using the Favourite subject column:**

In [ ]:
# Multiple conditions (OR)

    Name  Age Favorite_Subject  Test_Score
0  Alice   12             Math          85
1    Bob   11          Science          92
3  Diana   11             Math          88

# **Sorting Data:**

Explanation:
You can sort your data based on one or more columns.

**Sort the dataframe using the Test_Score**

In [ ]:
# Sort by test score (lowest to highest)

      Name  Age Favorite_Subject  Test_Score
2  Charlie   12              Art          83
3    Diana   11             Math          93
0    Alice   12             Math          95
1      Bob   11          Science          97
4      Eve   12          English         100

**Sort the dataframe using the Test_Score in descending order:**

In [ ]:
# Sort by test score (highest to lowest)

      Name  Age Favorite_Subject  Test_Score
4      Eve   12          English         100
1      Bob   11          Science          97
0    Alice   12             Math          95
3    Diana   11             Math          93
2  Charlie   12              Art          83

**Sort the column by Age in ascending order and Test_Score in descending order:**

In [ ]:
# Sort by multiple columns

      Name  Age Favorite_Subject  Test_Score
1      Bob   11          Science          92
3    Diana   11             Math          88
4      Eve   12          English          95
0    Alice   12             Math          85
2  Charlie   12              Art          78

# **Adding and Modifying Columns:**

Explanation: You can create or modify columns using basic operations.

In [ ]:
# Add a column showing if students passed (score >= 80)
df['Passed'] = df['Test_Score'] >= 80
df

# Add a grade column based on scores
def get_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    else:
        return 'D'

df['Grade'] = df['Test_Score'].apply(get_grade)
df

      Name  Age Favorite_Subject  Test_Score  Passed Grade
0    Alice   12             Math          85    True     B
1      Bob   11          Science          92    True     A
2  Charlie   12              Art          78   False     C
3    Diana   11             Math          88    True     B
4      Eve   12          English          95    True     A

### **Modifying Data :**

In [ ]:
# Change a specific value
df.loc[0, 'Test_Score'] = 90

# Add 5 bonus points to everyone
df['Test_Score'] = df['Test_Score'] + 5

df

      Name  Age Favorite_Subject  Test_Score
0    Alice   12             Math          95
1      Bob   11          Science          97
2  Charlie   12              Art          83
3    Diana   11             Math          93
4      Eve   12          English         100

### **Calculating Statistics :**

In [ ]:
# Average test score
average_score = df['Test_Score'].mean()
print(f"Average Score: {average_score}")

# Highest score
max_score = df['Test_Score'].max()
print(f"Highest Score: {max_score}")

# Lowest score
min_score = df['Test_Score'].min()
print(f"Lowest Score: {min_score}")

# Total of all scores
total = df['Test_Score'].sum()
print(f"Total: {total}")

# Count how many students
count = df['Name'].count()
print(f"Number of students: {count}")

Average Score: 93.6
Highest Score: 100
Lowest Score: 83
Total: 468
Number of students: 5

### **Grouping data:**

In [ ]:
# Average score by age
age_groups = df.groupby('Age')['Test_Score'].mean()
print(age_groups)
print('\n')

# Count students by favorite subject
subject_counts = df.groupby('Favorite_Subject').size()
print(subject_counts)
print('\n')

# Multiple statistics at once
summary = df.groupby('Favorite_Subject')['Test_Score'].agg(['mean', 'max', 'min'])
print(summary)

Age
11    95.000000
12    92.666667
Name: Test_Score, dtype: float64


Favorite_Subject
Art        1
English    1
Math       2
Science    1
dtype: int64


                   mean  max  min
Favorite_Subject
Art                83.0   83   83
English           100.0  100  100
Math               94.0   95   93
Science            97.0   97   97

# **Dropping Columns or Rows**

Explanation:
Use .drop() to remove rows or columns.

In [ ]:
df.drop('City', axis=1)   # Drop a column
df.drop(2, axis=0)        # Drop a row (index = 2)

KeyError: "['City'] not found in axis"

# **Handling Missing Data:**

Explanation:
Missing data can appear as NaN values. You can detect, replace, or remove them.

In [ ]:
# Create data with missing values (NaN = Not a Number)
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Score': [85, None, 78, 92],
    'Grade': ['B', 'A', None, 'A']
}

df = pd.DataFrame(data)
df

      Name  Score Grade
0    Alice   85.0     B
1      Bob    NaN     A
2  Charlie   78.0  None
3    Diana   92.0     A

In [ ]:
# Check for missing data
df.isnull()

    Name  Score  Grade
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [ ]:
# Count missing values in each column
df.isnull().sum()

Name     0
Score    1
Grade    1
dtype: int64

In [ ]:
# Drop rows with missing data
df_cleaned = df.dropna()
df_cleaned

    Name  Score Grade
0  Alice   85.0     B
3  Diana   92.0     A

In [ ]:
# Fill missing values with something
df_filled = df.fillna(0)  # Replace with 0
#df_filled = df.fillna('Unknown')  # Replace with 'Unknown'
df_filled

      Name  Score Grade
0    Alice   85.0     B
1      Bob    0.0     A
2  Charlie   78.0     0
3    Diana   92.0     A

In [ ]:
# Fill missing scores with the average
df['Score'] = df['Score'].fillna(df['Score'].mean())
df

      Name  Score Grade
0    Alice   85.0     B
1      Bob   85.0     A
2  Charlie   78.0  None
3    Diana   92.0     A

# **Merging and Joining DataFrames:**

Explanation:
Combine multiple DataFrames similar to SQL joins `(inner, left, right, outer)`.

In [ ]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Score': [85, 90, 75]})

merged = pd.merge(df1, df2, on='ID', how='inner')
merged

   ID   Name  Score
0   1  Alice     85
1   2    Bob     90

In [ ]:
left_merge = pd.merge(df1, df2, on='ID', how='left')
left_merge

   ID     Name  Score
0   1    Alice   85.0
1   2      Bob   90.0
2   3  Charlie    NaN

### 🟠 **Explanation:**

All records from `df1` are kept.

Since `Charlie (ID 3)` doesn’t exist in `df2`, the `Score` is `NaN`.

In [ ]:
right_merge = pd.merge(df1, df2, on='ID', how='right')
right_merge

   ID   Name  Score
0   1  Alice     85
1   2    Bob     90
2   4    NaN     75

### **🔵 Explanation:**

All records from `df2` are retained.

Since `ID 4` doesn’t exist in` df1`, `Name` is `NaN`.

In [ ]:
outer_merge = pd.merge(df1, df2, on='ID', how='outer')
outer_merge

   ID     Name  Score
0   1    Alice   85.0
1   2      Bob   90.0
2   3  Charlie    NaN
3   4      NaN   75.0

### **🟣 Explanation:**

Includes all `IDs` from both tables — missing matches are filled with `NaN`.

# **Concatenating DataFrames:**

Explanation:
Stack DataFrames vertically or horizontally.

In [ ]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

pd.concat([df1, df2])

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

# **Working with Dates:**

Explanation:
Convert strings to dates and extract components like year, month, and day.

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['London', 'Paris', 'Berlin', 'Madrid']
}
df = pd.DataFrame(data)

df['JoinDate'] = pd.to_datetime(['2021-01-10', '2021-03-15', '2021-05-20', '2021-07-10'])
df['Year'] = df['JoinDate'].dt.year
df['Month'] = df['JoinDate'].dt.month
df

      Name  Age    City   JoinDate  Year  Month
0    Alice   25  London 2021-01-10  2021      1
1      Bob   30   Paris 2021-03-15  2021      3
2  Charlie   35  Berlin 2021-05-20  2021      5
3    David   40  Madrid 2021-07-10  2021      7

# **Applying Functions:**

**Explanation:**
Apply a custom function to a column using `apply()`

In [ ]:
def age_category(age):
    return 'Young' if age < 30 else 'Senior'

df['Category'] = df['Age'].apply(age_category)
df

      Name   Age    City  Age in 5 years Category
0    Alice  25.0  London            30.0    Young
1      Bob  30.0   Paris            35.0   Senior
2  Charlie  35.0  Berlin            40.0   Senior

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace'],
    'Age': [25, 30, 35, 40, 28, 33, 29],
    'City': ['London', 'Paris', 'Berlin', 'Madrid', 'Rome', 'Oslo', 'Vienna']
}

df = pd.DataFrame(data)
df

      Name  Age    City
0    Alice   25  London
1      Bob   30   Paris
2  Charlie   35  Berlin
3    David   40  Madrid
4     Emma   28    Rome
5    Frank   33    Oslo
6    Grace   29  Vienna

In [ ]:
df.head()          # shows first 5 rows

      Name  Age    City
0    Alice   25  London
1      Bob   30   Paris
2  Charlie   35  Berlin
3    David   40  Madrid
4     Emma   28    Rome

In [ ]:
df.tail()          # shows last 5 rows. if you put any number inside the bracket it will show you that number of rows

      Name  Age    City
2  Charlie   35  Berlin
3    David   40  Madrid
4     Emma   28    Rome
5    Frank   33    Oslo
6    Grace   29  Vienna

Further Reading:
https://realpython.com/pandas-dataframe/#sorting-a-pandas-dataframe

Youtube video on Pandas: https://www.youtube.com/watch?v=2uvysYbKdjM

# **Please use the Part 2 .ipynb file to start working on the real world data (Assessment Data)**